"""Initial migrations create jobs table

Revision ID: e1d8dbedd791
Revises: 
Create Date: 2026-05-22 07:36:36.578874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d8dbedd791'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('media_url', sa.String(length=1024), nullable=True),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
